### ISSUE TITLE
Panic :)

### ISSUE THREAD

**Issue by monstariko** [V4NSH4J/discord-mass-DM-GO#442]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x80 pc=0x8b54fd]

goroutine 1863 [running]:
github.com/V4NSH4J/discord-mass-dm-GO/utilities.(*Connection).Close(0x0)
        D:/Desktop/Generic Folder Name/utilities/websocket.go:250 +0x1d
main.Options.func18(0xc0017babb0)
        D:/Desktop/Generic Folder Name/main.go:1433 +0x686
created by main.Options
        D:/Desktop/Generic Folder Name/main.go:1412 +0x4ff2
        
        While changing usernames.

**Comment by monstariko** [comment]
This error occurs when I change PFP or username. Changing the number of threads helped me.
