### ISSUE TITLE
error

### ISSUE THREAD

**Issue by poegod** [V4NSH4J/discord-mass-DM-GO#634]
![Uploading image.png…]()
I'm not able to mass dm

**Comment by poegod** [comment]
![image](https://user-images.githubusercontent.com/82784342/168819628-89461101-3f50-4df6-9d28-14934d21152b.png)

**Comment by V4NSH4J** [comment]
Turn off online_tokens in config

**Comment by TuanPhong15** [comment]
any update ?, i'm still get this error when pulling new code : @V4NSH4J 
` panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by V4NSH4J** [comment]
> any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`

Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.

**Comment by TuanPhong15** [comment]
> > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> 
> Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.

When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options, and it crashes with no log.

**Comment by V4NSH4J** [comment]
> > > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> > 
> > 
> > Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.
> 
> When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options of 10 - Scraping Menu -> 1 - Scraping online, fill token and server, channel id, and it crashes with no log.

1) Don't do go run (it won't work, you'll have to build from source and run the binary using go build)
2) pull [this](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b608dad75ba76c17c93446510f38ac3e074f67f4)

**Comment by poegod** [comment]
![image](https://user-images.githubusercontent.com/82784342/169278258-3c4916be-15db-416b-8dc1-c979d75f434b.png)
Any solution for this @V4NSH4J

**Comment by V4NSH4J** [comment]
> ![image](https://user-images.githubusercontent.com/82784342/169278258-3c4916be-15db-416b-8dc1-c979d75f434b.png) Any solution for this @V4NSH4J

You're rate limited, use proxies.

**Comment by poegod** [comment]
Thanks

**Comment by TuanPhong15** [comment]
> > > > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> > > 
> > > 
> > > Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.
> > 
> > 
> > When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options of 10 - Scraping Menu -> 1 - Scraping online, fill token and server, channel id, and it crashes with no log.
> 
> 1. Don't do go run (it won't work, you'll have to build from source and run the binary using go build)
> 2. pull [this](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b608dad75ba76c17c93446510f38ac3e074f67f4)

when i build it from code -> main.exe -> options 10 scrap member id ->option 1 scrap online -> enter tokens and channel id ->enter -> console crash with no warning. Can @V4NSH4J help me, I'm still stuck in this bug

**Comment by TuanPhong15** [comment]
> > > > > > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> > > > > 
> > > > > 
> > > > > Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.
> > > > 
> > > > 
> > > > When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options of 10 - Scraping Menu -> 1 - Scraping online, fill token and server, channel id, and it crashes with no log.
> > > 
> > > 
> > > 
> > > 1. Don't do go run (it won't work, you'll have to build from source and run the binary using go build)
> > > 2. pull [this](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b608dad75ba76c17c93446510f38ac3e074f67f4)
> > 
> > 
> > when i build it from code -> main.exe -> options 10 scrap member id ->option 1 scrap online -> enter tokens and channel id ->enter -> console crash with no warning. Can @V4NSH4J help me, I'm still stuck in this bug
> 
> Can you do this from a terminal/command prompt window? It'll show you the error before exiting.

Here is error log. please help me @V4NSH4J : go run main.go -> options 10 -> options 1 -> enter tokens,server id, channel id and it throws this massage:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x83c99b]

goroutine 21 [running]:
github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu.func1()
        D:/discord-mass-DM-GO/discord/scraper.go:50 +0x3b
created by github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu
        D:/discord-mass-DM-GO/discord/scraper.go:43 +0x451
exit status 2
```

**Comment by V4NSH4J** [comment]
> > > > > > > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> > > > > > 
> > > > > > 
> > > > > > Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.
> > > > > 
> > > > > 
> > > > > When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options of 10 - Scraping Menu -> 1 - Scraping online, fill token and server, channel id, and it crashes with no log.
> > > > 
> > > > 
> > > > 
> > > > 1. Don't do go run (it won't work, you'll have to build from source and run the binary using go build)
> > > > 2. pull [this](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b608dad75ba76c17c93446510f38ac3e074f67f4)
> > > 
> > > 
> > > when i build it from code -> main.exe -> options 10 scrap member id ->option 1 scrap online -> enter tokens and channel id ->enter -> console crash with no warning. Can @V4NSH4J help me, I'm still stuck in this bug
> > 
> > 
> > Can you do this from a terminal/command prompt window? It'll show you the error before exiting.
> 
> Here is error log. please help me @V4NSH4J : go run main.go -> options 10 -> options 1 -> enter tokens,server id, channel id and it throws this massage:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x8 pc=0x83c99b]
> 
> goroutine 21 [running]:
> github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu.func1()
>         D:/discord-mass-DM-GO/discord/scraper.go:50 +0x3b
> created by github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu
>         D:/discord-mass-DM-GO/discord/scraper.go:43 +0x451
> exit status 2
> ```

Hey, which version of DMDGO was this on?

**Comment by TuanPhong15** [comment]
> > > > > > > > any update ?, i'm still get this error when pulling new code : @V4NSH4J ` panic: runtime error: invalid memory address or nil pointer dereference`
> > > > > > > 
> > > > > > > 
> > > > > > > Hi I just pushed an update for it, it shouldn't crash anymore but I'm still looking for a permanent solution to it.
> > > > > > 
> > > > > > 
> > > > > > When I pull new code [b5fcf3a](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b5fcf3ae0ba361e9c124851841253af38dafb4af), go run main.go, and choose some options of 10 - Scraping Menu -> 1 - Scraping online, fill token and server, channel id, and it crashes with no log.
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. Don't do go run (it won't work, you'll have to build from source and run the binary using go build)
> > > > > 2. pull [this](https://github.com/V4NSH4J/discord-mass-DM-GO/commit/b608dad75ba76c17c93446510f38ac3e074f67f4)
> > > > 
> > > > 
> > > > when i build it from code -> main.exe -> options 10 scrap member id ->option 1 scrap online -> enter tokens and channel id ->enter -> console crash with no warning. Can @V4NSH4J help me, I'm still stuck in this bug
> > > 
> > > 
> > > Can you do this from a terminal/command prompt window? It'll show you the error before exiting.
> > 
> > 
> > Here is error log. please help me @V4NSH4J : go run main.go -> options 10 -> options 1 -> enter tokens,server id, channel id and it throws this massage:
> > ```
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal 0xc0000005 code=0x0 addr=0x8 pc=0x83c99b]
> > 
> > goroutine 21 [running]:
> > github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu.func1()
> >         D:/discord-mass-DM-GO/discord/scraper.go:50 +0x3b
> > created by github.com/V4NSH4J/discord-mass-dm-GO/discord.LaunchScraperMenu
> >         D:/discord-mass-DM-GO/discord/scraper.go:43 +0x451
> > exit status 2
> > ```
> 
> Hey, which version of DMDGO was this on?

 You're Up-to-Date! You're using DMDGO V1.10.0. V1.10.0 sir.

**Comment by TuanPhong15** [comment]
thanks you so much @V4NSH4J , you made my day !!!

**Comment by TuanPhong15** [comment]
@V4NSH4J hello sir, anti-capcha is not work can u switch it into capmonster
